codecov:
  token: 6fb9a259-b7c4-4690-9894-8496238ef9f2
  branch: master

comment:
  layout: header, changes, diff

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    patch: false
