version: '2'

services:
    haproxy:
        image: haproxy:1.7
        ports:
            # stats
            - "8036:8036"

            # splash
            - "8050:8050"
        links:
            - splash0
            - splash1
            - splash2
            - splash3
            - splash4
        volumes:
            - D:/host/transistor/appveyor/aquarium/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro

    splash0:
        image: scrapinghub/splash:master
        command: --max-timeout 3600 --slots 8 --maxrss 3000 --verbosity 1
        expose:
            - 8050
        mem_limit: 4200m
        memswap_limit: 5400m
        restart: always
        links:
            - tor
        volumes:
            - D:/host/transistor/appveyor/aquarium/proxy-profiles:/etc/splash/proxy-profiles:ro
            - D:/host/transistor/appveyor/aquarium/filters:/etc/splash/filters:ro

    splash1:
        image: scrapinghub/splash:master
        command: --max-timeout 3600 --slots 8 --maxrss 3000 --verbosity 1
        expose:
            - 8050
        mem_limit: 4200m
        memswap_limit: 5400m
        restart: always
        links:
            - tor
        volumes:
            - D:/host/transistor/appveyor/aquarium/proxy-profiles:/etc/splash/proxy-profiles:ro
            - D:/host/transistor/appveyor/aquarium/filters:/etc/splash/filters:ro

    splash2:
        image: scrapinghub/splash:master
        command: --max-timeout 3600 --slots 8 --maxrss 3000 --verbosity 1
        expose:
            - 8050
        mem_limit: 4200m
        memswap_limit: 5400m
        restart: always
        links:
            - tor
        volumes:
            - D:/host/transistor/appveyor/aquarium/proxy-profiles:/etc/splash/proxy-profiles:ro
            - D:/host/transistor/appveyor/aquarium/filters:/etc/splash/filters:ro

    splash3:
        image: scrapinghub/splash:master
        command: --max-timeout 3600 --slots 8 --maxrss 3000 --verbosity 1
        expose:
            - 8050
        mem_limit: 4200m
        memswap_limit: 5400m
        restart: always
        links:
            - tor
        volumes:
            - D:/host/transistor/appveyor/aquarium/proxy-profiles:/etc/splash/proxy-profiles:ro
            - D:/host/transistor/appveyor/aquarium/filters:/etc/splash/filters:ro

    splash4:
        image: scrapinghub/splash:master
        command: --max-timeout 3600 --slots 8 --maxrss 3000 --verbosity 1
        expose:
            - 8050
        mem_limit: 4200m
        memswap_limit: 5400m
        restart: always
        links:
            - tor
        volumes:
            - D:/host/transistor/appveyor/aquarium/proxy-profiles:/etc/splash/proxy-profiles:ro
            - D:/host/transistor/appveyor/aquarium/filters:/etc/splash/filters:ro

    tor:
        image: jess/tor-proxy
        expose:
            - 9050
        logging:
            driver: "none"
        restart: always

    
